FROM ruby:4.0-slim

RUN apt-get update -qq && apt-get install --no-install-recommends -y build-essential libpq-dev postgresql-client curl && rm -rf /var/lib/apt/lists/*
WORKDIR /rails
COPY Gemfile Gemfile.lock* ./
RUN bundle install
COPY . .
RUN SECRET_KEY_BASE_DUMMY=1 bin/rails assets:precompile
EXPOSE 3000
CMD ["./bin/rails", "server", "-b", "0.0.0.0"]
